# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout TPTP-ANTLR
      uses: actions/checkout@v4
      with:
          path: TPTP-ANTLR

    - name: checkout SigmaUtils
      uses: actions/checkout@v4
      with:
        repository: 'ontologyportal/SigmaUtils'
        path: SigmaUtils

    - name: Set up JDK 21 on x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Ant
      run: ant
      working-directory: ./TPTP-ANTLR

    - name: Prep ENV and run unit tests
      run: ant test
      env:
        ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
      working-directory: ./TPTP-ANTLR
